spring:
  application:
    name: SpringCloundConfigApplication
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joncabrerasu/shared-config-properties.git
server:
  port: 8888